'use strict';
const assert = require('node:assert/strict');
const model = require('../common/calendar/availability-model.js');
const date = '2030-01-07';
const people = Array.from({length: 5}, (_, index) => ({
    id: String(index), name: 'Person ' + index,
    days: {[date]: '0'.repeat(18) + (index === 0 ? '2' : '1') + (index < 4 ? '2' : '1') + '11' + '0'.repeat(26)}
}));
let result = model.aggregateDay(people, date);
assert.equal(result.state, 'partial');
assert.equal(result.slots.length, 4);
assert.equal(result.workingCount, 4);
assert.equal(result.busySlotCount, 2, 'A slot counts once whether one or four people are busy.');
assert.deepEqual(result.slots.map(slot => slot.busyCount), [1, 4, 0, 0]);
assert.deepEqual(result.slots[0].busyNames, ['Person 0']);
assert.deepEqual(result.slots[1].busyNames, ['Person 0', 'Person 1', 'Person 2', 'Person 3']);
assert.ok(model.occupationHue(1, 5) > model.occupationHue(4, 5), 'One busy person is closer to yellow than four.');
assert.equal(model.occupationHue(5, 5), 0, 'All busy is red.');
result = model.aggregateDay(people.slice(1), date);
assert.equal(result.slots[0].busy, false, 'Excluding the conflicting person frees the slot.');
assert.deepEqual(result.slots[0].busyNames, [], 'Excluded people disappear from hover names.');
assert.equal(result.slots[1].busyCount, 3);
assert.equal(result.slots[1].participantCount, 4);
assert.equal(model.aggregateDay([people[4]], date).state, 'free');
assert.equal(result.busySlotCount, 1, 'Excluding a person recalculates the daily ratio too.');
assert.deepEqual(model.aggregateDay([], date), {state: 'closed', slots: [], workingCount: 0, busySlotCount: 0});
assert.deepEqual(model.aggregateDay(people, '2030-01-08'), {state: 'closed', slots: [], workingCount: 0, busySlotCount: 0});
const pausePerson = {name: 'Pause', days: {[date]: '0'.repeat(19) + '31' + '0'.repeat(27)}};
result = model.aggregateDay([people[4], pausePerson], date);
assert.equal(result.slots.length, 2, 'Only common working hours are visible.');
assert.equal(result.slots[0].pause, true);
assert.equal(result.state, 'free', 'Pauses do not count as calendar conflicts.');
assert.equal(result.workingCount, 1, 'Pauses are excluded from the daily denominator.');
assert.equal(result.busySlotCount, 0);
const mostlyFree = {days: {[date]: '0'.repeat(18) + '21111111' + '0'.repeat(22)}};
const mostlyBusy = {days: {[date]: '0'.repeat(18) + '22222221' + '0'.repeat(22)}};
const freeDay = model.aggregateDay([mostlyFree], date);
const busyDay = model.aggregateDay([mostlyBusy], date);
assert.equal(freeDay.busySlotCount, 1);
assert.equal(busyDay.busySlotCount, 7);
assert.ok(model.occupationHue(freeDay.busySlotCount, freeDay.workingCount) > model.occupationHue(busyDay.busySlotCount, busyDay.workingCount));
const rangeSlots = [true, true, true, true, false, true].map((free, index) => ({free, start: index, end: index + 1}));
assert.deepEqual(model.selectRange(rangeSlots, 0, 3), {first: 0, last: 2}, '90 minutes selects clicked half-hour and two following.');
assert.deepEqual(model.selectRange(rangeSlots, 2, 3), {first: 1, last: 3}, 'Range slides backwards if the following slots are occupied.');
assert.deepEqual(model.selectRange(rangeSlots, 3, 3), {first: 1, last: 3}, 'At closing, use the two preceding free slots.');
assert.equal(model.selectRange(rangeSlots, 5, 3), null, 'An isolated free slot cannot create a 90-minute appointment.');
assert.equal(model.selectRange(rangeSlots, 4, 1), null, 'A busy clicked slot is never selected.');
assert.equal(model.selectRange([{free: true, start: 0, end: 1}, {free: true, start: 2, end: 3}], 0, 2), null, 'Cannot cross an omitted pause or working-hour gap.');
const buffered = [0, 1, 2, 3].map(index => ({free: true, start: index, end: index + 1,
    beforeFree: index > 0, afterFree: index < 3}));
assert.equal(model.selectRange(buffered, 0, 1), null, 'Preparation cannot precede opening.');
assert.deepEqual(model.selectRange(buffered, 1, 2), {first: 1, last: 2}, 'Longer appointments validate buffers at their actual ends.');
assert.equal(model.selectRange(buffered, 3, 1), null, 'Closing cannot follow the final available slot.');
assert.deepEqual(model.selectRange(buffered, 2, 2), {first: 1, last: 2}, 'Backward fitting accounts for closing time.');
console.log('calendar_availability_model_test: OK');
