'use strict';
const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
let accepted = false;
let confirmations = 0;
const context = { window: { confirm: () => { confirmations++; return accepted; } }, fetch: () => Promise.resolve({ ok: false }) };
vm.createContext(context);
vm.runInContext(fs.readFileSync('common/assets/property-list-conversion.js', 'utf8'), context);
const conversion = context.window.omoPropertyListConversion;
const draft = { id: 5, formatId: 7, listItemType: 'authority', value: '{"before":"Intro","items":["123","Budget"],"after":"End"}' };
const field = { value: 'authority' };
assert.strictEqual(conversion.change(draft, 'text', field), false);
assert.strictEqual(field.value, 'text');
assert.strictEqual(draft.listConversionFrom, undefined);
const original = draft.value;
accepted = true;
field.value = 'authority';
assert.strictEqual(conversion.change(draft, 'text', field), true);
assert.strictEqual(draft.value, original);
assert.strictEqual(draft.listConversionFrom, 'text');
assert.strictEqual(conversion.sourceProperty(draft).listItemType, 'text');
field.value = 'number';
assert.strictEqual(conversion.change(draft, 'authority', field), false);
assert.strictEqual(field.value, 'authority');
field.value = 'text';
assert.strictEqual(conversion.change(draft, 'authority', field), true);
assert.strictEqual(draft.listConversionFrom, undefined);
assert.strictEqual(draft.value, original);
assert.strictEqual(confirmations, 2);
const fresh = { id: 0, formatId: 2, value: '["123","Budget"]' };
field.value = 'authority';
assert.strictEqual(conversion.change(fresh, 'text', field), true);
assert.deepStrictEqual(JSON.parse(fresh.value), [{ label: '123', isLocal: true }, { label: 'Budget', isLocal: true }]);
const reverse = { id: 5, formatId: 2, value: '[7,9]' };
field.value = 'text';
assert.strictEqual(conversion.change(reverse, 'authority', field), true);
assert.strictEqual(reverse.value, '[7,9]');
assert.strictEqual(reverse.listConversionFrom, 'authority');

// Exercise the real template change handler with its old text inputs still in the DOM.
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<div class="omo-template-property" data-property-id="5"><input class="omo-template-property__name" value="Domains"><select class="omo-template-property__format"><option value="2" selected>List</option></select><select class="omo-template-property__list-item-type"><option value="text">Text</option><option value="authority" selected>Authority</option></select><input class="omo-template-property__value-item" value="123"><input class="omo-template-property__value-item" value="Budget"></div>');
const row = dom.window.document.querySelector('div');
row.dataset.listItemType = 'text';
context.document = dom.window.document;
context.row = row;
context.propertyField = row.querySelector('.omo-template-property__list-item-type');
context.omoHolonTemplateIsHolonDefinitionMode = () => false;
context.omoHolonTemplateGetAuthorityCatalog = () => [];
context.omoHolonTemplateCreatePropertyRow = property => { context.captured = property; return row.cloneNode(true); };
const templateSource = fs.readFileSync('omo/api/parameters/holon-templates/templates.js', 'utf8');
for (const name of ['omoHolonTemplateSerializePropertyValue', 'omoHolonTemplateReadPropertyState']) {
    const start = templateSource.indexOf('function ' + name + '(');
    const end = templateSource.indexOf('\nfunction ', start + 1);
    vm.runInContext(templateSource.slice(start, end), context);
}
const start = templateSource.indexOf('        const previousType = String(row.dataset.listItemType');
const end = templateSource.indexOf('        row.replaceWith(replacement);', start) + '        row.replaceWith(replacement);'.length;
vm.runInContext('(function () {' + templateSource.slice(start, end) + '\n})();', context);
assert.strictEqual(context.captured.value, '["123","Budget"]', 'Changing the select must read text inputs before switching serializers');
assert.strictEqual(context.captured.listConversionFrom, 'text');

const pendingRow = dom.window.document.createElement('div');
pendingRow.innerHTML = '<select class="format"></select><div class="values"><input value="123"><button>Add</button></div>';
conversion.mount(pendingRow, context.captured, '.values', '.format');
assert.strictEqual(pendingRow.dataset.conversionValue, '["123","Budget"]');
assert(pendingRow.querySelector('.format').disabled);
assert(pendingRow.querySelector('.values input').disabled);
assert.strictEqual(context.omoHolonTemplateSerializePropertyValue(pendingRow, 2, 'authority'), '["123","Budget"]');
console.log('property_list_conversion_test: OK');
