<?php

use PhpOffice\PhpWord\Style;
use PhpOffice\PhpWord\Style\Font;
use PhpOffice\PhpWord\Style\Paragraph;

/**
 * Complete the ODT styles and inline lists omitted by PHPWord 1.4's writer.
 * Call immediately after ODText::save(), while its generated styles exist.
 * Only operates on the temporary package generated by this application.
 */
function commonCompletePhpWordOdt(string $path, float $fontSize): void
{
    $namespaces = [
        'office' => 'urn:oasis:names:tc:opendocument:xmlns:office:1.0',
        'style' => 'urn:oasis:names:tc:opendocument:xmlns:style:1.0',
        'text' => 'urn:oasis:names:tc:opendocument:xmlns:text:1.0',
        'fo' => 'urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0',
    ];
    $zip = new ZipArchive();
    if ($zip->open($path) !== true) {
        throw new RuntimeException('Unable to open generated ODT.');
    }

    try {
        foreach (['content.xml', 'styles.xml'] as $part) {
            $xml = $zip->getFromName($part);
            $document = new DOMDocument('1.0', 'UTF-8');
            if (!is_string($xml) || !$document->loadXML($xml, LIBXML_NONET)) {
                throw new RuntimeException('Invalid generated ODT part: ' . $part);
            }
            $xpath = new DOMXPath($document);
            foreach ($namespaces as $prefix => $uri) {
                $xpath->registerNamespace($prefix, $uri);
            }
            $setAttributes = static function (DOMElement $node, array $attributes) use ($namespaces): void {
                foreach ($attributes as $name => $value) {
                    $prefix = explode(':', $name, 2)[0];
                    $node->setAttributeNS($namespaces[$prefix], $name, (string)$value);
                }
            };
            $properties = static function (DOMElement $style, string $name) use ($document, $xpath, $namespaces): DOMElement {
                $node = $xpath->query('style:' . $name, $style)->item(0);
                if (!$node instanceof DOMElement) {
                    $node = $document->createElementNS($namespaces['style'], 'style:' . $name);
                    $style->appendChild($node);
                }
                return $node;
            };

            foreach ($xpath->query('//style:style') as $node) {
                $style = Style::getStyle($node->getAttributeNS($namespaces['style'], 'name'));
                $family = $node->getAttributeNS($namespaces['style'], 'family');
                if ($style instanceof Font && $family === 'text') {
                    $fill = $style->getShading()?->getFill();
                    if (is_string($fill) && preg_match('/^[a-f0-9]{6}$/i', $fill)) {
                        $setAttributes($properties($node, 'text-properties'), ['fo:background-color' => '#' . $fill]);
                    }
                } elseif ($style instanceof Paragraph && $family === 'paragraph') {
                    $attributes = [];
                    $fill = $style->getShading()?->getFill();
                    if (is_string($fill) && preg_match('/^[a-f0-9]{6}$/i', $fill)) {
                        $attributes['fo:background-color'] = '#' . $fill;
                    }
                    if ($style->isKeepNext()) {
                        $attributes['fo:keep-with-next'] = 'always';
                    }
                    if ($style->isKeepLines()) {
                        $attributes['fo:keep-together'] = 'always';
                    }
                    foreach (['Top', 'Right', 'Bottom', 'Left'] as $side) {
                        $size = $style->{'getBorder' . $side . 'Size'}();
                        $color = $style->{'getBorder' . $side . 'Color'}() ?? '000000';
                        if (is_numeric($size) && $size > 0 && preg_match('/^[a-f0-9]{6}$/i', $color)) {
                            $attributes['fo:border-' . strtolower($side)] = ($size / 8) . 'pt solid #' . $color;
                        }
                    }
                    $setAttributes($properties($node, 'paragraph-properties'), $attributes);
                }
            }

            if ($part === 'styles.xml') {
                $officeStyles = $xpath->query('/office:document-styles/office:styles')->item(0);
                if (!$officeStyles instanceof DOMElement) {
                    throw new RuntimeException('Missing ODT styles.');
                }
                // HTML import refers to Heading1..6 without defining these styles.
                $definitions = ['Normal' => [1, false, 0, 6]];
                foreach ([1 => 1.6, 2 => 1.2, 3 => 1.17, 4 => 1, 5 => .83, 6 => .67] as $level => $scale) {
                    $definitions['Heading' . $level] = [$scale, $level > 2, $level === 1 ? 0 : 12, 6];
                }
                foreach ($definitions as $name => [$scale, $bold, $before, $after]) {
                    if ($xpath->query('style:style[@style:name="' . $name . '" and @style:family="paragraph"]', $officeStyles)->length > 0) {
                        continue;
                    }
                    $node = $document->createElementNS($namespaces['style'], 'style:style');
                    $setAttributes($node, ['style:name' => $name, 'style:family' => 'paragraph']);
                    $officeStyles->appendChild($node);
                    $setAttributes($properties($node, 'paragraph-properties'), [
                        'fo:margin-top' => $before . 'pt',
                        'fo:margin-bottom' => $after . 'pt',
                        'fo:line-height' => '115%',
                        'fo:keep-with-next' => $name === 'Normal' ? 'auto' : 'always',
                    ]);
                    $setAttributes($properties($node, 'text-properties'), [
                        'style:font-name' => 'Arial',
                        'fo:font-size' => round($fontSize * $scale, 2) . 'pt',
                        'fo:font-weight' => $bold ? 'bold' : 'normal',
                        'fo:color' => '#202124',
                    ]);
                }
            } else {
                // The writer emits one paragraph per inline run in ListItemRun.
                // Join adjacent runs, preserving explicit line breaks and sublists.
                foreach ($xpath->query('//text:list-item') as $item) {
                    $paragraph = null;
                    foreach (iterator_to_array($item->childNodes) as $child) {
                        if (!$child instanceof DOMElement) {
                            continue;
                        }
                        if ($child->namespaceURI !== $namespaces['text'] || $child->localName !== 'p') {
                            $paragraph = null;
                            continue;
                        }
                        if ($paragraph === null) {
                            $paragraph = $child;
                            if (!$child->hasChildNodes() && $child->getAttributeNS($namespaces['text'], 'style-name') === 'Standard') {
                                $paragraph->appendChild($document->createElementNS($namespaces['text'], 'text:line-break'));
                            }
                        } else {
                            if (!$child->hasChildNodes()) {
                                $paragraph->appendChild($document->createElementNS($namespaces['text'], 'text:line-break'));
                            }
                            while ($child->firstChild !== null) {
                                $paragraph->appendChild($child->firstChild);
                            }
                            $item->removeChild($child);
                        }
                    }
                }
                // Consecutive items of the same source list must share numbering.
                foreach (iterator_to_array($xpath->query('//text:list')) as $list) {
                    if ($list->parentNode === null) {
                        continue;
                    }
                    $next = $list->nextSibling;
                    while ($next instanceof DOMElement && $next->namespaceURI === $namespaces['text']
                        && $next->localName === 'list'
                        && $next->getAttributeNS($namespaces['text'], 'style-name') === $list->getAttributeNS($namespaces['text'], 'style-name')) {
                        while ($next->firstChild !== null) {
                            $list->appendChild($next->firstChild);
                        }
                        $next->parentNode->removeChild($next);
                        $next = $list->nextSibling;
                    }
                }
                // Whitespace between HTML blocks is not an empty PV paragraph.
                foreach (iterator_to_array($xpath->query('//text:p[text:span/text:tab]')) as $paragraph) {
                    if (trim($paragraph->textContent) === ''
                        && $xpath->query('.//*[not(self::text:span or self::text:tab or self::text:s)]', $paragraph)->length === 0) {
                        $paragraph->parentNode->removeChild($paragraph);
                    }
                }
            }

            $updatedXml = $document->saveXML();
            if ($updatedXml === false || !$zip->addFromString($part, $updatedXml)) {
                throw new RuntimeException('Unable to update ODT part: ' . $part);
            }
        }
    } finally {
        if (!$zip->close()) {
            throw new RuntimeException('Unable to save completed ODT.');
        }
    }
}
