window.commonPageScripts = window.commonPageScripts || {};
window.commonPageScripts["/omo/api/deferred_proposals/pv_proposal_picker.js"] = function (pageConfig, pageScript) {
(function(){
const root=document.querySelector('[data-deferred-proposal-workflow]');if(!root)return;
const operation=root.querySelector('[data-deferred-operation]'),contextLabel=root.querySelector('[data-deferred-context-label]'),objectRow=root.querySelector('[data-deferred-object-row]'),objectSelect=root.querySelector('[data-deferred-object]'),createRow=root.querySelector('[data-deferred-create-row]'),feedback=root.querySelector('[data-deferred-feedback]');
const pickerLayer=root.querySelector('[data-deferred-context-picker]'),pickerHost=root.querySelector('[data-deferred-context-map]'),candidateLabel=root.querySelector('[data-deferred-context-candidate-label]'),candidateStatus=root.querySelector('[data-deferred-context-candidate-status]'),chooseContext=root.querySelector('[data-deferred-context-choose]');
const labels=pageConfig.labels,permissions=pageConfig.contextPermissions,projectCreationModes=pageConfig.projectCreationModes,buttonLabels=pageConfig.buttonLabels,texts=pageConfig.tr;
const initialObjectId=pageConfig.initialObjectId,proposalId=pageConfig.proposalId,selectionLocked=proposalId>0;let targetType=pageConfig.targetType,contextId=pageConfig.contextHolonId,candidateContextId=contextId,picker=null,contextRequest=0,initialObjectPending=initialObjectId;
function allowedContextIds(){const byType=permissions[targetType]||{},ids=byType[operation.value];return Array.isArray(ids)?ids.map(Number):[]}function contextAllowed(id){return allowedContextIds().indexOf(Number(id))!==-1}function showFeedback(message){feedback.hidden=!message;feedback.textContent=message||''}
function updateTypeButtons(){root.querySelectorAll('[data-deferred-target-type]').forEach(function(button){const selected=button.getAttribute('data-deferred-target-type')===targetType;button.classList.toggle('is-selected',selected);button.setAttribute('aria-pressed',selected?'true':'false')})}function chooseDefaultContext(){const ids=allowedContextIds();if(!contextAllowed(contextId))contextId=ids.length?Number(ids[0]):0;contextLabel.value=String(labels[String(contextId)]||'')}
function updateLaunchButtons(){const labelsForType=buttonLabels[targetType]||{};const isProjectProposal=targetType==='project'&&operation.value==='create'&&String(projectCreationModes[String(contextId)]||'')==='propose';const label=String(isProjectProposal?labelsForType.propose:labelsForType[operation.value]||'');root.querySelectorAll('[data-deferred-open-editor]').forEach(function(button){button.textContent=label;button.disabled=!contextAllowed(contextId)||(operation.value!=='create'&&!Number(objectSelect.value||0))})}
function replaceObjects(items,selectedId){objectSelect.innerHTML='';(Array.isArray(items)?items:[]).forEach(function(item){const option=document.createElement('option');option.value=String(item.id||'');option.textContent=String(item.label||'');if(item.typeLabel)option.textContent+=' — '+String(item.typeLabel);if(Number(item.id)===Number(selectedId))option.selected=true;objectSelect.appendChild(option)});if(!objectSelect.options.length){const option=document.createElement('option');option.value='';option.textContent=texts.empty;objectSelect.appendChild(option);objectSelect.disabled=true}else objectSelect.disabled=selectionLocked;updateLaunchButtons()}
function loadObjects(){const requestId=++contextRequest;showFeedback('');chooseDefaultContext();const isCreate=operation.value==='create';objectRow.hidden=isCreate;createRow.hidden=!isCreate;updateLaunchButtons();if(!contextAllowed(contextId)){replaceObjects([],0);return Promise.resolve(false)}const selectedId=initialObjectPending;initialObjectPending=0;if(isCreate){replaceObjects([],0);updateLaunchButtons();return Promise.resolve(true)}objectSelect.disabled=true;objectSelect.innerHTML='<option>'+texts.loading+'</option>';const url=("/omo/api/deferred_proposals/pv_proposal_context.php?oid=" + pageConfig.organizationId + "&point_id=" + pageConfig.pointId + "&target_type=")+encodeURIComponent(targetType)+'&operation='+encodeURIComponent(operation.value)+'&context_holon_id='+encodeURIComponent(String(contextId));return fetch(url,{credentials:'same-origin'}).then(function(response){return response.json().then(function(payload){return{ok:response.ok,payload:payload}})}).then(function(result){if(requestId!==contextRequest)return false;if(!result.ok||!result.payload.status)throw new Error(result.payload.message||texts.loadError);if(result.payload.context&&result.payload.context.label){labels[String(contextId)]=String(result.payload.context.label);contextLabel.value=String(result.payload.context.label)}replaceObjects(result.payload.objects,selectedId);return true}).catch(function(error){if(requestId===contextRequest){replaceObjects([],0);showFeedback(error.message||texts.loadError)}return false})}
function updateCandidate(id){candidateContextId=Number(id||0);const allowed=contextAllowed(candidateContextId);candidateLabel.textContent=String(labels[String(candidateContextId)]||(picker&&picker.getSelectedHolonLabel?picker.getSelectedHolonLabel():'')||'');candidateStatus.textContent=allowed?texts.allowed:texts.denied;chooseContext.disabled=!allowed}function closePicker(){pickerLayer.hidden=true;if(picker&&typeof picker.destroy==='function')picker.destroy();picker=null;pickerHost.innerHTML=''}function openPicker(){if(typeof window.omoMountHolonScopePicker!=='function'){showFeedback(texts.editorError);return}candidateContextId=contextId;pickerLayer.hidden=false;picker=window.omoMountHolonScopePicker({host:pickerHost,organizationId:pageConfig.organizationId,initialHolonId:contextId,selectableHolonIds:allowedContextIds(),showModes:false,initialScope:'local',labelMode:'context',suppressInitialChange:true,onChange:updateCandidate,onReady:updateCandidate});updateCandidate(contextId)}
function buildEditorUrl(){const objectId=Number(objectSelect.value||0),common=("direct=1&oid=" + pageConfig.organizationId + "&point_id=" + pageConfig.pointId + "&proposal_id=")+proposalId+'&operation='+encodeURIComponent(operation.value);if(targetType==='rule')return'/omo/api/deferred_proposals/pv_rule_editor.php?workflow=1&'+common+'&holon_id='+encodeURIComponent(String(contextId))+'&rule_id='+encodeURIComponent(String(objectId));if(targetType==='project')return'/omo/api/deferred_proposals/pv_project_editor.php?stage=capture&'+common+'&holon_id='+encodeURIComponent(String(contextId))+'&project_id='+encodeURIComponent(String(objectId));if(targetType==='recurring_task'||targetType==='indicator')return'/omo/api/deferred_proposals/pv_object_editor.php?stage=capture&'+common+'&target_type='+encodeURIComponent(targetType)+'&holon_id='+encodeURIComponent(String(contextId))+'&object_id='+encodeURIComponent(String(objectId));return'/omo/api/deferred_proposals/pv_holon_editor.php?stage=capture&'+common+'&holon_id='+encodeURIComponent(String(operation.value==='create'?contextId:objectId))}
function openEditor(){if(!contextAllowed(contextId)||(operation.value!=='create'&&!Number(objectSelect.value||0)))return;showFeedback('');if(typeof window.commonTopbarRefreshModalContent!=='function'){showFeedback(texts.editorError);return}window.commonTopbarRefreshModalContent(buildEditorUrl())}
root.querySelectorAll('[data-deferred-target-type]').forEach(function(button){button.addEventListener('click',function(){if(button.disabled)return;targetType=String(button.getAttribute('data-deferred-target-type')||'rule');initialObjectPending=0;updateTypeButtons();chooseDefaultContext();loadObjects()})});operation.addEventListener('change',function(){initialObjectPending=0;chooseDefaultContext();loadObjects()});objectSelect.addEventListener('change',updateLaunchButtons);root.querySelectorAll('[data-deferred-open-editor]').forEach(function(button){button.addEventListener('click',openEditor)});root.querySelector('[data-deferred-context-open]').addEventListener('click',openPicker);root.querySelectorAll('[data-deferred-context-close]').forEach(function(button){button.addEventListener('click',closePicker)});pickerLayer.addEventListener('click',function(event){if(event.target===pickerLayer)closePicker()});chooseContext.addEventListener('click',function(){if(!contextAllowed(candidateContextId))return;contextId=candidateContextId;contextLabel.value=String(labels[String(contextId)]||candidateLabel.textContent||'');closePicker();initialObjectPending=0;loadObjects()});updateTypeButtons();chooseDefaultContext();loadObjects();
}());
};
