-- @migration

CREATE TABLE IF NOT EXISTS `user_patreon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `IDuser` int(11) NOT NULL,
  `access_token` text DEFAULT NULL,
  `refresh_token` text DEFAULT NULL,
  `token_expires_at` datetime DEFAULT NULL,
  `scope` varchar(255) DEFAULT NULL,
  `token_type` varchar(50) DEFAULT NULL,
  `patreon_user_id` varchar(50) DEFAULT NULL,
  `patreon_member_id` varchar(100) DEFAULT NULL,
  `campaign_id` varchar(50) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `profile_url` varchar(500) DEFAULT NULL,
  `vanity` varchar(255) DEFAULT NULL,
  `patron_status` varchar(50) DEFAULT NULL,
  `last_charge_status` varchar(50) DEFAULT NULL,
  `last_charge_date` datetime DEFAULT NULL,
  `next_charge_date` datetime DEFAULT NULL,
  `currently_entitled_amount_cents` int(11) NOT NULL DEFAULT 0,
  `campaign_lifetime_support_cents` int(11) NOT NULL DEFAULT 0,
  `tier_titles` mediumtext DEFAULT NULL,
  `is_connected` tinyint(1) NOT NULL DEFAULT 0,
  `connected_at` datetime DEFAULT NULL,
  `last_sync_at` datetime DEFAULT NULL,
  `last_sync_status` varchar(50) DEFAULT NULL,
  `last_sync_error` mediumtext DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_patreon_user` (`IDuser`),
  KEY `idx_user_patreon_connected` (`is_connected`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
