-- @migration
ALTER TABLE `event`
    ADD COLUMN IF NOT EXISTS `preparation_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `closing_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `meeting_profile`
    ADD COLUMN IF NOT EXISTS `preparation_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `closing_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `meeting_booking`
    ADD COLUMN IF NOT EXISTS `preparation_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `closing_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `external_calendar_event`
    ADD COLUMN IF NOT EXISTS `preparation_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `closing_minutes` SMALLINT UNSIGNED NOT NULL DEFAULT 0;
