-- @migration
SET NAMES utf8mb4;

UPDATE `faq`
SET
    `isactive` = 0,
    `updated` = NOW()
WHERE `id` IN (1, 2)
  AND `IDorganization` IS NULL
  AND (`IDholon` IS NULL OR `IDholon` = 0)
  AND `displayorder` = 0
  AND `created` = '2026-04-12 08:08:05';

INSERT INTO `faq` (
    `id`,
    `IDhowto`,
    `IDorganization`,
    `IDholon`,
    `question`,
    `answer`,
    `detail`,
    `displayorder`,
    `isactive`,
    `created`,
    `updated`
) VALUES
    (
        3201,
        NULL,
        NULL,
        NULL,
        'Comment ouvrir les outils d aide dans OMO ?',
        'Ouvrez le bouton Aide dans la topbar pour retrouver la FAQ, les tutoriels et la visite guidee.',
        '<p>La zone Aide centralise les ressources utiles quand vous avez un doute ou que vous decouvrez un ecran.</p><p>La FAQ donne des reponses rapides, les tutoriels vont plus loin et la visite guidee explique les boutons visibles sur la page en cours.</p>',
        10,
        1,
        '2026-06-22 09:00:00',
        '2026-06-22 09:00:00'
    ),
    (
        3202,
        NULL,
        NULL,
        NULL,
        'Comment utiliser la recherche de la topbar ?',
        'Tapez quelques mots cles dans la recherche puis ouvrez le resultat qui correspond a votre besoin.',
        '<p>La recherche de la topbar sert a retrouver rapidement un cercle, un role, un outil ou un acces utile.</p><p>Si plusieurs modules sont proposes, commencez par ceux qui correspondent a votre besoin puis affinez avec des mots simples et precis.</p>',
        20,
        1,
        '2026-06-22 09:05:00',
        '2026-06-22 09:05:00'
    ),
    (
        3203,
        NULL,
        NULL,
        NULL,
        'Comment changer ma langue ou mon theme ?',
        'Ouvrez le menu Profil dans la topbar pour regler la langue et le theme d affichage.',
        '<p>Le menu Profil permet de retrouver les reglages personnels les plus utiles sans quitter votre espace de travail.</p><p>Vous pouvez y adapter la langue de l interface et choisir le theme qui vous convient le mieux pour votre usage quotidien.</p>',
        30,
        1,
        '2026-06-22 09:10:00',
        '2026-06-22 09:10:00'
    ),
    (
        3204,
        NULL,
        NULL,
        NULL,
        'A quoi sert le switch Local / Enfants directs / Descendants ?',
        'Il permet d afficher le holon courant seul, avec ses enfants directs ou avec tous ses descendants.',
        '<p>Le mode Local affiche uniquement les elements lies au holon courant.</p><p>Enfants directs ajoute les elements lies a ses enfants, tandis que Descendants couvre tout son sous-arbre.</p>',
        40,
        1,
        '2026-06-22 09:15:00',
        '2026-06-22 09:15:00'
    ),
    (
        3205,
        NULL,
        NULL,
        NULL,
        'Comment passer du tri Date au tri Alphabetique ?',
        'Utilisez le controle de tri dans l entete du drawer pour choisir l ordre qui vous aide le plus.',
        '<p>Le tri par date est utile pour revoir ce qui vient d etre cree ou modifie recemment.</p><p>Le tri alphabetique est souvent plus confortable quand vous cherchez un nom connu dans une longue liste.</p>',
        50,
        1,
        '2026-06-22 09:20:00',
        '2026-06-22 09:20:00'
    ),
    (
        3206,
        NULL,
        NULL,
        NULL,
        'A quoi sert le mode Detail / Compact ?',
        'Le mode Detail montre plus d informations par carte, tandis que Compact affiche plus d elements a l ecran.',
        '<p>Choisissez Detail quand vous voulez lire les resumes, les metadonnees ou mieux comparer plusieurs cartes.</p><p>Choisissez Compact quand vous voulez parcourir beaucoup d elements rapidement, en particulier sur mobile ou dans une colonne etroite.</p>',
        60,
        1,
        '2026-06-22 09:25:00',
        '2026-06-22 09:25:00'
    ),
    (
        3207,
        NULL,
        NULL,
        NULL,
        'Comment creer un document dans OMO ?',
        'Ouvrez l app Documents puis utilisez le bouton Ajouter si votre role vous y autorise.',
        '<p>Sur grand ecran, le bouton de creation apparait dans l entete du module. Sur mobile, il peut etre reduit a une icone en haut a droite.</p><p>Si vous ne voyez pas ce bouton, cela signifie en general que votre contexte actuel ou vos droits ne permettent pas cette creation.</p>',
        70,
        1,
        '2026-06-22 09:30:00',
        '2026-06-22 09:30:00'
    ),
    (
        3208,
        NULL,
        NULL,
        NULL,
        'Comment modifier un document existant ?',
        'Ouvrez le document puis lancez l action Editer depuis le drawer ou le menu prevu.',
        '<p>L edition passe par le formulaire du document et enregistre les changements dans le contexte de ce document.</p><p>Si un document appartient deja a une organisation ou a un holon, les droits de ce contexte continuent a s appliquer au moment de la sauvegarde.</p>',
        80,
        1,
        '2026-06-22 09:35:00',
        '2026-06-22 09:35:00'
    ),
    (
        3209,
        NULL,
        NULL,
        NULL,
        'A quoi sert l app Memo ?',
        'Memo rassemble vos documents personnels et vos notes dans une vue simple a parcourir.',
        '<p>La liste Memo peut regrouper les documents dont vous etes l auteur, y compris quand ils proviennent de plusieurs holons.</p><p>Le detail se consulte ensuite dans un drawer interne, ce qui permet de rester dans le meme espace sans ouvrir une nouvelle page.</p>',
        90,
        1,
        '2026-06-22 09:40:00',
        '2026-06-22 09:40:00'
    ),
    (
        3210,
        NULL,
        NULL,
        NULL,
        'Comment reediter un memo depuis l app Memo ?',
        'Ouvrez le menu ... sur un memo puis choisissez Editer.',
        '<p>L action Editer ouvre le formulaire du memo dans un drawer, avec un parcours proche de celui du module Documents.</p><p>Les memos sans contexte d organisation peuvent etre reedites par leur auteur, alors que les documents deja classes gardent les droits de leur contexte habituel.</p>',
        100,
        1,
        '2026-06-22 09:45:00',
        '2026-06-22 09:45:00'
    ),
    (
        3211,
        NULL,
        NULL,
        NULL,
        'Comment terminer ou classer un memo depuis Telegram ?',
        'Utilisez les boutons proposes par le bot pour choisir une destination autorisee ou terminer dans le contexte courant.',
        '<p>Le bot ne propose que les destinations de classement qui restent autorisees pour votre contexte et vos droits.</p><p>Si le bouton Terminer ici ou certaines destinations ne sont pas visibles, cela signifie simplement que cette action nest pas disponible pour vous a cet endroit.</p>',
        110,
        1,
        '2026-06-22 09:50:00',
        '2026-06-22 09:50:00'
    ),
    (
        3212,
        NULL,
        NULL,
        NULL,
        'Comment creer une prise de decision ?',
        'Ouvrez l app Decisions puis utilisez le bouton de creation disponible dans l entete si vous avez le droit necessaire.',
        '<p>La creation se fait dans le contexte courant, par exemple pour une organisation, un cercle ou un autre niveau de structure.</p><p>Prenez le temps de definir un titre clair, une description utile et les dates importantes avant de lancer la participation.</p>',
        120,
        1,
        '2026-06-22 09:55:00',
        '2026-06-22 09:55:00'
    ),
    (
        3213,
        NULL,
        NULL,
        NULL,
        'Comment participer a une decision avec un lien public ou un acces personnel ?',
        'Ouvrez la page de participation recue par lien ou demandez votre acces personnel depuis l ecran public du scrutin.',
        '<p>Certaines decisions peuvent accepter la participation sans invitation classique, directement depuis un lien public partage par l organisateur.</p><p>Si ce nest pas le cas, utilisez la page Recevoir mon acces personnel pour demander un lien individuel avant de voter.</p>',
        130,
        1,
        '2026-06-22 10:00:00',
        '2026-06-22 10:00:00'
    ),
    (
        3214,
        NULL,
        NULL,
        NULL,
        'Comment noter des propositions en jugement majoritaire ?',
        'Attribuez une mention a chaque proposition selon l echelle affichee, de la plus favorable a la moins favorable.',
        '<p>Le jugement majoritaire ne consiste pas a choisir une seule proposition. Vous evaluez chaque option avec la meme echelle.</p><p>Le resultat final compare ensuite la repartition des mentions pour aider a faire ressortir la proposition la plus solide.</p>',
        140,
        1,
        '2026-06-22 10:05:00',
        '2026-06-22 10:05:00'
    ),
    (
        3215,
        NULL,
        NULL,
        NULL,
        'Comment ajouter un evenement dans le calendrier ?',
        'Ouvrez le calendrier puis utilisez le bouton Ajouter si votre contexte vous autorise a creer des dates.',
        '<p>Comme pour les autres modules, le bouton peut etre plein texte sur grand ecran ou reduit a une icone sur mobile.</p><p>Si vous ne pouvez pas creer de date a cet endroit, changez de contexte ou demandez a une personne administratrice de verifier vos droits.</p>',
        150,
        1,
        '2026-06-22 10:10:00',
        '2026-06-22 10:10:00'
    ),
    (
        3216,
        NULL,
        NULL,
        NULL,
        'Comment changer de vue dans le calendrier ?',
        'Utilisez le selecteur Mois, Semaine, Jour ou Liste pour choisir la lecture la plus pratique.',
        '<p>Chaque vue repond a un besoin different: Mois pour la planification generale, Semaine ou Jour pour le detail, Liste pour un balayage rapide.</p><p>Sur mobile, ces vues peuvent apparaitre sous forme d icones plus compactes afin de laisser davantage de place au contenu.</p>',
        160,
        1,
        '2026-06-22 10:15:00',
        '2026-06-22 10:15:00'
    ),
    (
        3217,
        NULL,
        NULL,
        NULL,
        'Pourquoi je ne vois pas toujours le bouton Ajouter ?',
        'Le bouton apparait seulement si vous avez la permission de creation dans le contexte ouvert.',
        '<p>Ce principe vaut notamment pour les documents, les prises de decision, les dates et la creation de FAQ.</p><p>Si vous pensez que ce bouton devrait etre disponible, verifiez le contexte courant ou demandez une verification des permissions sur le holon concerne.</p>',
        170,
        1,
        '2026-06-22 10:20:00',
        '2026-06-22 10:20:00'
    ),
    (
        3218,
        NULL,
        NULL,
        NULL,
        'Comment ajouter une question dans la FAQ ?',
        'Ouvrez la FAQ du contexte voulu puis utilisez le bouton Ajouter une question si cette action est disponible.',
        '<p>Selon votre ecran, la nouvelle question peut etre creee au niveau du contexte courant, du niveau organisation ou dans un scope plus global.</p><p>Si aucun bouton de creation ne saffiche, cela signifie que la permission de creation de FAQ nest pas accordee dans ce contexte.</p>',
        180,
        1,
        '2026-06-22 10:25:00',
        '2026-06-22 10:25:00'
    ),
    (
        3219,
        NULL,
        NULL,
        NULL,
        'A quoi servent les votes sur les reponses de la FAQ ?',
        'Les boutons de vote permettent de signaler si une reponse est utile afin de mieux mettre en avant les bonnes explications.',
        '<p>Quand une reponse vous aide vraiment, un vote positif aide a la faire remonter dans la FAQ.</p><p>Ces retours servent a rendre les questions les plus utiles plus visibles pour les autres membres de l organisation.</p>',
        190,
        1,
        '2026-06-22 10:30:00',
        '2026-06-22 10:30:00'
    ),
    (
        3220,
        NULL,
        NULL,
        NULL,
        'Comment faire apparaitre mon organisation sur la carte publique ?',
        'Renseignez un emplacement dans les parametres de l organisation et verifiez que les informations utiles sont lisibles sans connexion.',
        '<p>La carte publique utilise un emplacement facultatif, generalement saisi en latitude et longitude dans les parametres de l organisation.</p><p>Seules les informations explicitement exposees comme publiques sont reprises sur cette carte, ce qui permet de garder le controle sur ce qui est visible sans connexion.</p>',
        200,
        1,
        '2026-06-22 10:35:00',
        '2026-06-22 10:35:00'
    )
ON DUPLICATE KEY UPDATE
    `IDhowto` = VALUES(`IDhowto`),
    `IDorganization` = VALUES(`IDorganization`),
    `IDholon` = VALUES(`IDholon`),
    `question` = VALUES(`question`),
    `answer` = VALUES(`answer`),
    `detail` = VALUES(`detail`),
    `displayorder` = VALUES(`displayorder`),
    `isactive` = VALUES(`isactive`),
    `updated` = VALUES(`updated`);
