name: Deploy Dev

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Infomaniak
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            cd ~/sites/dev.opengov.tools
            git fetch origin Dev
            git reset --hard origin/Dev
